default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "H9Z8PM46JZ",
      issuer_id: "61771d9b-ea3e-409d-9d3b-c4ee05e77ae8",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_H9Z8PM46JZ.p8")
    )
    
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_options: {
        method: "app-store-connect",
        signingStyle: "automatic",
        teamID: "52WXM3TBJ4"
      }
    )
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Build and upload to App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "H9Z8PM46JZ",
      issuer_id: "61771d9b-ea3e-409d-9d3b-c4ee05e77ae8",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_H9Z8PM46JZ.p8")
    )
    
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_options: {
        method: "app-store-connect",
        signingStyle: "automatic",
        teamID: "52WXM3TBJ4"
      }
    )
    upload_to_app_store(
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false
    )
  end

  desc "Upload existing IPA to App Store"
  lane :upload do
    api_key = app_store_connect_api_key(
      key_id: "H9Z8PM46JZ",
      issuer_id: "61771d9b-ea3e-409d-9d3b-c4ee05e77ae8",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_H9Z8PM46JZ.p8")
    )
    
    upload_to_app_store(
      api_key: api_key,
      ipa: "../build/ios/ipa/learn_by_heart.ipa",
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false
    )
  end

  desc "Upload metadata only"
  lane :metadata do
    api_key = app_store_connect_api_key(
      key_id: "H9Z8PM46JZ",
      issuer_id: "61771d9b-ea3e-409d-9d3b-c4ee05e77ae8",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_H9Z8PM46JZ.p8")
    )

    upload_to_app_store(
      api_key: api_key,
      skip_binary_upload: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
      run_precheck_before_submit: false,
      force: true
    )
  end

  desc "Upload screenshots only"
  lane :screenshots do
    api_key = app_store_connect_api_key(
      key_id: "H9Z8PM46JZ",
      issuer_id: "61771d9b-ea3e-409d-9d3b-c4ee05e77ae8",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_H9Z8PM46JZ.p8")
    )

    upload_to_app_store(
      api_key: api_key,
      skip_binary_upload: true,
      skip_metadata: true,
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false,
      run_precheck_before_submit: false,
      force: true
    )
  end
end
